[package]
name = "perm_comp_bench"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
permutation_compression = {"path" = "../"}
rand = "0.8.4"
bytesize = "1.1.0"

[profile.release]
debug = true